language: python

stages:
  - name: publish
    if: tag IS present

jobs:
  include:
    - name: Build package and publish to PyPI
      stage: publish
      install:
        - pip3 install --upgrade pip
        - pip3 install twine pyopenssl
      script:
        - python3 setup.py bdist_wheel && twine upload dist/*py3-none-any* -u $PYPI_LOGIN -p $PYPI_PASS
